### ISSUE TITLE
Joined players

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#10]
## Description
Need to know how many players are in the game as this effects the rules.

## Todo
- [x] Keep a list of players that have had an approved edit.
- [ ] Or is this about whose voted?
- [ ] Maybe we just need the num players but don't need to know who they are. Although we need to know who they are so that we know if it's a new player edit or an existing player edit.
