### ISSUE TITLE
Add initial picture to IPFS

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#3]
## Description
We need a way to add a picture to the IPFS and get it's address back.

## Setup
- [x] Install [IPFS](https://docs.ipfs.io/guides/guides/install/)
- [x] Test putting image in

## Todo
- [ ] Create a substrate UI
- [ ] Add the IPFS js node
- [ ] Test adding image to IPFS through this browser js calls
- [ ] Add a browse and add picture UI
- [ ] Test adding image to IPFS through this UI
- [ ] Add to the IPFS and store it's hash

**Comment by freesig** [comment]
Looks like [js](https://js.ipfs.io/) might be a better way of interacting with IPFS.
I think maybe I should crate a substrate React UI and add this module with a UI component that allows the user to add a picture to IPFS

**Comment by freesig** [comment]
Another option is https://polkadot.js.org/api/METHODS_RPC.html#json-rpc

**Comment by freesig** [comment]
Currently the js-ipfs isn't working for me, I will just manually enter pictures into ipfs now to test and then come back to making an interface for this process

**Comment by freesig** [comment]
I think the ipfs hash can probably be stored as H256
