### ISSUE TITLE
Start game by adding rules and initial picture address

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#4]
## Description
We need to be able to add the rules to an (Immutable store?) in the chain. This needs to be done at the start of the chain so that the first block contains these rules and the initial image hash.

## Todo
- [ ] Hard code in these values to get a working prototype
- [x] Make a function to set these initially

__Nice to haves__
- [ ] UI for setting rules.
- [ ] Take the hash from #3 and add it to this.
- [ ] Maybe this is only done once or maybe there is an authority to who can change it
- [ ] Submit the initial block and lunch the chain.

**Comment by freesig** [comment]
- Critique Credits: u32
Minimum number required to submit an edit.
- Votes: u32
Minimum number required accept an edit.
- Initial Time Limit: time::Duration
How long to wait before submitting an edit.

**Comment by freesig** [comment]
Could use [this](https://substrate.dev/rustdocs/v1.0/srml_timestamp/index.html) to store time
