### ISSUE TITLE
Submit Edit to IPFS

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#5]
## Description
Allow the players to submit edits. Edits are just a new image hash.

## Todo
- [x] Add ability to submit an edit
- [x] Where do we store an edit?
- [x] Add abiltiy to add edited image to IPFS

**Comment by freesig** [comment]
How to store the IPFS hash? Maybe as a String but I don't think we can store strings so it might have to be a `Vec<u8>` or maybe there is a hash type we can use.

Just use string for now
