### ISSUE TITLE
Add Critique Credits

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#6]
## Description
Critique Credits allow users to submit edits. They are earned by voting.

## Todo
- [ ] Prevent edits from being submitted without minimum CCs.
- [ ] Store each players CCs.
- [ ] Spend CCs when an edit is submitted.
