### ISSUE TITLE
Add Voting

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#7]
## Description
Allow users to vote to earn CCs.

## Todo
- [ ] UI that compares edit to current image
- [ ] UI that user can submit a vote.
- [ ] Add vote to pending Edit into the chain
- [ ] Submit edit when minimum votes is reached
