### ISSUE TITLE
Initial Time Limit

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#8]
## Description
Add a time limit to get the game started. This prevents edits from being blocked by lack of players.

## Todo
- [ ] Set initial time limit in the rules of the game
- [ ] Increase time limit as more players join
- [ ] Set maximum time limit and when reached time limit is disabled
- [ ] Submit edits that reach their time limit
