### ISSUE TITLE
Conflict resolution

### ISSUE THREAD

**Issue by freesig** [freesig/pixel_chain#9]
## Description
If two pending edits change the same pixel then when voting the player needs to see all the options.

## Todo
- [ ] Work out the best way to handle this?
- [ ] Maybe show all edits that conflict so they can make a better vote
- [ ] Would need to batch pending edits into voting pools so that the voters can see all possibilities for that pool
